# Generated by Django 3.2.16 on 2024-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthday_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
